import 'reflect-metadata';
import { Output } from './Output';
export * from 'trucolor';
export * from './colors';
export * from './ui';
export * from './utils';
export * from './figures';
export * from './interfaces';
export * from './macros';
export * from './Output';
export * from './OutputServiceProvider';
export declare const out: Output;
